networks:
  net:
    driver: bridge

services:
  website:
    build: website
    ports:
      - "3000:80"
    environment:
      - API_URL=http://server:5000
    networks:
      - net

  server:
    build: backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_PORT}
    networks:
      - net
    depends_on:
      - postgres

  migrate:
    build: migrate
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_PORT}
    profiles:
      - migrate
    networks:
      - net

  postgres:
    image: "postgres:17-alpine3.20"
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - net